name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install meson ninja

    - name: Setup build
      run: meson setup build

    - name: Build
      run: ninja -C build

    - name: Run tests
      run: meson test -C build

    - name: Upload meson test log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: meson-testlog
        path: build/meson-logs/testlog.txt
        if-no-files-found: warn
